(foreign-declare "#include <tesselator.h>") 

;;; GENERATED BY CHICKEN-BIND FROM tesselator.h

(module tesselator *
  (import chicken scheme foreign)
  (define TESS_WINDING_ODD 0)
  (define TESS_WINDING_NONZERO 1)
  (define TESS_WINDING_POSITIVE 2)
  (define TESS_WINDING_NEGATIVE 3)
  (define TESS_WINDING_ABS_GEQ_TWO 4)
  (define TESS_POLYGONS 0)
  (define TESS_CONNECTED_POLYGONS 1)
  (define TESS_BOUNDARY_CONTOURS 2)
  (define TESSalloc-userData
    (foreign-lambda*
      (c-pointer void)
      (((c-pointer (struct "TESSalloc")) s))
      "return(s->userData);"))
  (define TESSalloc-meshEdgeBucketSize
    (foreign-lambda*
      integer
      (((c-pointer (struct "TESSalloc")) s))
      "return(s->meshEdgeBucketSize);"))
  (define TESSalloc-meshVertexBucketSize
    (foreign-lambda*
      integer
      (((c-pointer (struct "TESSalloc")) s))
      "return(s->meshVertexBucketSize);"))
  (define TESSalloc-meshFaceBucketSize
    (foreign-lambda*
      integer
      (((c-pointer (struct "TESSalloc")) s))
      "return(s->meshFaceBucketSize);"))
  (define TESSalloc-dictNodeBucketSize
    (foreign-lambda*
      integer
      (((c-pointer (struct "TESSalloc")) s))
      "return(s->dictNodeBucketSize);"))
  (define TESSalloc-regionBucketSize
    (foreign-lambda*
      integer
      (((c-pointer (struct "TESSalloc")) s))
      "return(s->regionBucketSize);"))
  (define TESSalloc-extraVertices
    (foreign-lambda*
      integer
      (((c-pointer (struct "TESSalloc")) s))
      "return(s->extraVertices);"))
  (define make-TESSalloc
    (foreign-lambda*
      (c-pointer (struct "TESSalloc"))
      (((c-pointer void) userData)
       (integer meshEdgeBucketSize)
       (integer meshVertexBucketSize)
       (integer meshFaceBucketSize)
       (integer dictNodeBucketSize)
       (integer regionBucketSize)
       (integer extraVertices))
      "struct TESSalloc *tmp_ =  (struct TESSalloc *)C_malloc(sizeof(struct TESSalloc));\ntmp_->userData = userData;\ntmp_->meshEdgeBucketSize = meshEdgeBucketSize;\ntmp_->meshVertexBucketSize = meshVertexBucketSize;\ntmp_->meshFaceBucketSize = meshFaceBucketSize;\ntmp_->dictNodeBucketSize = dictNodeBucketSize;\ntmp_->regionBucketSize = regionBucketSize;\ntmp_->extraVertices = extraVertices;\nreturn(tmp_);;\n"))
  (begin
    (define tessNewTess
      (foreign-lambda*
        (c-pointer (struct "TESStesselator"))
        (((c-pointer (struct "TESSalloc")) a0))
        "return(tessNewTess(a0));")))
  (begin
    (define tessDeleteTess
      (foreign-lambda*
        void
        (((c-pointer (struct "TESStesselator")) a0))
        "tessDeleteTess(a0);")))
  (begin
    (define tessAddContour
      (foreign-lambda*
        void
        (((c-pointer (struct "TESStesselator")) a0)
         (integer a1)
         ((c-pointer void) a2)
         (integer a3)
         (integer a4))
        "tessAddContour(a0 , a1 , a2 , a3 , a4);")))
  (begin
    (define tessTesselate
      (foreign-lambda*
        integer
        (((c-pointer (struct "TESStesselator")) a0)
         (integer a1)
         (integer a2)
         (integer a3)
         (integer a4)
         (f32vector a5))
        "return(tessTesselate(a0 , a1 , a2 , a3 , a4 , a5));")))
  (begin
    (define tessGetVertexCount
      (foreign-lambda*
        integer
        (((c-pointer (struct "TESStesselator")) a0))
        "return(tessGetVertexCount(a0));")))
  (begin
    (define tessGetVertices
      (foreign-lambda*
        (c-pointer (const float))
        (((c-pointer (struct "TESStesselator")) a0))
        "return(tessGetVertices(a0));")))
  (begin
    (define tessGetVertexIndices
      (foreign-lambda*
        (c-pointer (const integer))
        (((c-pointer (struct "TESStesselator")) a0))
        "return(tessGetVertexIndices(a0));")))
  (begin
    (define tessGetElementCount
      (foreign-lambda*
        integer
        (((c-pointer (struct "TESStesselator")) a0))
        "return(tessGetElementCount(a0));")))
  (begin
    (define tessGetElements
      (foreign-lambda*
        (c-pointer (const integer))
        (((c-pointer (struct "TESStesselator")) a0))
        "return(tessGetElements(a0));"))))

;;; END OF FILE
